name: Generate a PDF

on: push

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    name: Generate PDF resume
    steps:
      - uses: actions/checkout@v3
      - run: |
          apt install -y pandoc texlive-luatex fonts-ipafont
          pandoc content/resume.md -o dist/resume.pdf --pdf-engine=lualatex -V documentclass=ltjsarticle -V luatexjapresetoptions=ipa
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/resume.pdf
