name: Generate a PDF

on: push

jobs:
  generate-resume:
    runs-on: ubuntu-latest
    name: Generate PDF resume
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update && sudo apt-get install -y pandoc texlive-full texlive-luatex fonts-ipafont
          mkdir -p dist && sed '1,11d' content/resume.md > dist/resume.md
          pandoc dist/resume.md -o dist/resume.pdf --pdf-engine=lualatex -V luatexjapresetoptions=ipa
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/resume.pdf
